apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: hello-api
    kind: Deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20