apiVersion: v1
kind: Service
metadata:
  name: hello-api-service
spec:
  selector:
    app: hello-api
  type: ClusterIP
  ports:
    - name: hello-api-service
      port: 80
      targetPort: 5001
      protocol: TCP